name: Arch Linux Repository Builder

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # روزانه اجرا شود

jobs:
  build-repo:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    # مرحله 1: دریافت مخزن با تمام تاریخچه
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # مرحله 2: تنظیم محیط ساخت و نصب وابستگی‌های عمومی
    - name: Setup build environment
      run: |
        pacman -Sy --noconfirm --needed git base-devel pacman-contrib
        pacman -S --noconfirm --needed \
          hicolor-icon-theme libayatana-appindicator at-spi2-core \
          fontconfig pango gtk3 ayatana-ido gdk-pixbuf2 \
          libayatana-indicator libdbusmenu-glib cairo harfbuzz libepoxy \
          python python-gobject python-pycountry gtk4 libadwaita tractor meson

    # مرحله 3: ایجاد کاربر builder بدون نیاز به رمز عبور
    - name: Create builder user
      run: |
        useradd -m builder
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

    # مرحله 4: دریافت و ساخت بسته‌های AUR
    - name: Clone and build AUR packages
      run: |
        # ساخت hiddify-app-bin
        git clone https://aur.archlinux.org/hiddify-app-bin.git
        cd hiddify-app-bin
        chown -R builder .
        su builder -c "makepkg -s --noconfirm --skippgpcheck"
        cd ..
        
        # ساخت carburetor
        git clone https://aur.archlinux.org/carburetor.git
        cd carburetor
        chown -R builder .
        su builder -c "makepkg -s --noconfirm --skippgpcheck"
        cd ..

    # مرحله 5: آماده‌سازی ریپازیتوری
    - name: Prepare repository structure
      run: |
        mkdir -p repo/x86_64
        mv hiddify-app-bin/*.pkg.tar.zst repo/x86_64/
        mv carburetor/*.pkg.tar.zst repo/x86_64/
        cd repo/x86_64
        repo-add zc-repo.db.tar.gz *.pkg.tar.zst

    # مرحله 6: آپلود به شاخه repo
    - name: Deploy to repository branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.UPLOAD_ZENORA }}
        publish_dir: ./repo
        destination_dir: .
        publish_branch: repo
        keep_files: false
        force_orphan: true
