name: Arch Linux Repository Builder

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # روزانه اجرا شود

jobs:
  build-repo:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    # مرحله 1: دریافت مخزن با تمام تاریخچه
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # مرحله 2: تنظیم محیط ساخت و نصب yay
    - name: Setup build environment
      run: |
        pacman -Sy --noconfirm --needed git base-devel
        # نصب وابستگی‌های اولیه
        pacman -S --noconfirm --needed \
          hicolor-icon-theme libayatana-appindicator at-spi2-core \
          fontconfig pango gtk3 ayatana-ido gdk-pixbuf2 \
          libayatana-indicator libdbusmenu-glib cairo harfbuzz libepoxy \
          python python-gobject python-pycountry gtk4 libadwaita meson
        
        # نصب yay
        git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si --noconfirm --skippgpcheck
        cd ..

    # مرحله 3: ساخت بسته‌های AUR با yay
    - name: Build AUR packages with yay
      run: |
        # ساخت hiddify-app-bin
        yay -S --noconfirm --builddir=./ --mflags="--skippgpcheck" hiddify-app-bin
        
        # ساخت carburetor
        yay -S --noconfirm --builddir=./ --mflags="--skippgpcheck" carburetor

    # مرحله 4: آماده‌سازی ریپازیتوری
    - name: Prepare repository structure
      run: |
        mkdir -p repo/x86_64
        find . -name "*.pkg.tar.zst" -exec mv {} repo/x86_64/ \;
        cd repo/x86_64
        repo-add zc-repo.db.tar.gz *.pkg.tar.zst

    # مرحله 5: آپلود به شاخه repo
    - name: Deploy to repository branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.UPLOAD_ZENORA }}
        publish_dir: ./repo
        destination_dir: .
        publish_branch: repo
        keep_files: false
        force_orphan: true
