name: Arch Linux Repository Builder

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily

jobs:
  build-repo:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository with LFS
      uses: actions/checkout@v4
      with:
        lfs: true

    # Step 2: Setup build environment
    - name: Setup build environment
      run: |
        pacman -Rdd --noconfirm systemd-sysvcompat || true
        pacman -Sy --noconfirm --needed git git-lfs base-devel
        pacman -S --noconfirm --needed \
          hicolor-icon-theme libayatana-appindicator at-spi2-core \
          fontconfig pango gtk3 ayatana-ido gdk-pixbuf2 \
          libayatana-indicator libdbusmenu-glib cairo harfbuzz libepoxy \
          python python-gobject python-pycountry gtk4 libadwaita meson \
          cmake ninja qt6-base qt6-wayland vulkan-headers libdrm libxcb \
          polkit

    # Step 3: Install yay as builder user
    - name: Install yay as builder user
      run: |
        useradd -m builder
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        
        sudo -u builder git clone https://aur.archlinux.org/yay.git /tmp/yay
        cd /tmp/yay
        sudo -u builder makepkg -si --noconfirm --skippgpcheck
        rm -rf /tmp/yay

    # Step 4: Build AUR packages with yay
    - name: Build AUR packages with yay
      run: |
        cd "$GITHUB_WORKSPACE"
        sudo -u builder yay -S --noconfirm --builddir=/tmp --mflags="--skippgpcheck" hiddify-app-bin
        sudo -u builder yay -S --noconfirm --builddir=/tmp --mflags="--skippgpcheck" carburetor
        sudo -u builder yay -S --noconfirm --builddir=/tmp --mflags="--skippgpcheck" lact-git
        sudo -u builder yay -S --noconfirm --builddir=/tmp --mflags="--skippgpcheck" oblivion-desktop-bin

    # Step 5: Prepare repository structure with LFS
    - name: Prepare repository structure with LFS
      run: |
        # Install and setup Git LFS
        git lfs install
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        mkdir -p "$GITHUB_WORKSPACE/repo/x86_64"
        find /tmp -name "*.pkg.tar.zst" -exec mv {} "$GITHUB_WORKSPACE/repo/x86_64/" \;
        
        cd "$GITHUB_WORKSPACE/repo"
        git lfs track "x86_64/*.pkg.tar.zst"
        git add .gitattributes
        
        cd x86_64
        repo-add zc-repo.db.tar.gz *.pkg.tar.zst
        git add .

    # Step 6: Deploy to repository branch with LFS support
    - name: Deploy to repository branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.UPLOAD_ZENORA }}
        publish_dir: ./repo
        destination_dir: .
        publish_branch: repo
        keep_files: false
        force_orphan: true
        enable_jekyll: false
