name: Build and Deploy AUR Package

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Daily build

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: source

    - name: Setup environment
      run: |
        sed -i 's/^CheckSpace/#CheckSpace/' /etc/pacman.conf
        echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
        pacman -Sy --noconfirm --needed git base-devel pacman-contrib \
          hicolor-icon-theme libayatana-appindicator at-spi2-core \
          fontconfig pango gtk3 ayatana-ido gdk-pixbuf2 \
          libayatana-indicator libdbusmenu-glib cairo harfbuzz libepoxy

    - name: Clone AUR package
      run: |
        git clone https://aur.archlinux.org/hiddify-app-bin.git

    - name: Build package
      working-directory: ./hiddify-app-bin
      run: |
        useradd -m builder
        chown -R builder .
        su builder -c "makepkg -s --noconfirm --skippgpcheck"

    - name: Prepare repository files
      run: |
        mkdir -p repo-content/x86_64
        mv hiddify-app-bin/*.pkg.tar.zst repo-content/x86_64/
        cd repo-content/x86_64
        repo-add hiddify-repo.db.tar.gz *.pkg.tar.zst

    - name: Initialize Git Repository
      run: |
        mkdir -p github-repo
        cd github-repo
        git init
        git remote add origin https://github.com/${{ github.repository }}.git

    - name: Configure and Push to Repo Branch
      run: |
        cd github-repo
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # Check if repo branch exists
        if git ls-remote --exit-code --heads origin repo; then
          git fetch origin repo
          git checkout repo
        else
          git checkout --orphan repo
        fi
        
        # Remove existing files
        find . -mindepth 1 -delete
        
        # Copy new files
        cp -r ../repo-content/x86_64/* .
        
        # Commit and push
        git add -A
        git commit -m "Repo update: $(date +'%Y-%m-%d %H:%M:%S')"
        git push -f origin repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
