name: zenora ARM64 AUR Repository Builder

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'  # اجرای روزانه ساعت 03:00 UTC

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
    # مرحله 0: فعال‌سازی QEMU برای معماری ARM64
    - name: Enable QEMU for aarch64
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    # مرحله 1: دریافت کد پروژه
    - name: Checkout repository
      uses: actions/checkout@v4

    # مرحله 2: اجرای کانتینر Arch ARM با QEMU
    - name: Run ARM64 build in container
      uses: addnab/docker-run-action@v3
      with:
        image: archlinux:base-devel
        options: --platform linux/arm64
        shell: bash
        run: |
          pacman -Sy --noconfirm git base-devel sudo wget

          # ساخت کاربر builder
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

          # نصب yay
          sudo -u builder git clone https://aur.archlinux.org/yay.git /tmp/yay
          cd /tmp/yay
          sudo -u builder makepkg -si --noconfirm --skippgpcheck
          rm -rf /tmp/yay

          # مسیر خروجی
          mkdir -p /tmp/aarch64
          cd /home/builder

          # لیست بسته‌ها مناسب ARM64
          packages=(
            carburetor
            ascii-draw
            materialgram-bin
            gopeed-bin
          )

          for pkg in "${packages[@]}"; do
            sudo -u builder yay -S --noconfirm --mflags="--skippgpcheck" --builddir=/tmp/aarch64 "$pkg"
          done

    # مرحله 3: کلون فقط پوشه aarch64 از مخزن Codeberg
    - name: Clone only aarch64 folder (sparse checkout)
      env:
        CODEBERG_USER: zenoralinux
        CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
      run: |
        # پاکسازی توکن
        CLEAN_TOKEN=$(echo "$CODEBERG_TOKEN" | tr -d '\n\r\t ')

        git init existing_repo
        cd existing_repo

        git remote add origin "https://${CODEBERG_USER}:${CLEAN_TOKEN}@codeberg.org/${CODEBERG_USER}/zc-repo.git"
        git config core.sparseCheckout true
        echo "zcrepo/aarch64/" >> .git/info/sparse-checkout
        git pull --depth=1 origin main

    # مرحله 4: کپی بسته‌ها و ساخت دیتابیس
    - name: Sync and update repo database
      run: |
        mkdir -p existing_repo/zcrepo/aarch64
        find /tmp/aarch64 -name "*.pkg.tar.zst" -exec cp -f {} existing_repo/zcrepo/aarch64/ \;

        cd existing_repo/zcrepo/aarch64
        rm -f zc-repo.db* zc-repo.files*
        repo-add zc-repo.db.tar.gz *.pkg.tar.zst
        mv zc-repo.db.tar.gz zc-repo.db
        mv zc-repo.files.tar.gz zc-repo.files

    # مرحله 5: Push به Codeberg
    - name: Commit and push changes
      run: |
        cd existing_repo
        git add .
        git commit -m "ARM64 repo update: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push origin main
