name: Arch Linux Repository Builder

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # روزانه اجرا شود

jobs:
  build-repo:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    # مرحله 1: دریافت مخزن
    - name: Checkout repository
      uses: actions/checkout@v4

    # مرحله 2: تنظیم محیط ساخت
    - name: Setup build environment
      run: |
        pacman -Rdd --noconfirm systemd-sysvcompat || true
        pacman -Sy --noconfirm --needed git base-devel pacman-contrib
        pacman -S --noconfirm --needed \
          hicolor-icon-theme libayatana-appindicator at-spi2-core \
          fontconfig pango gtk3 ayatana-ido gdk-pixbuf2 \
          libayatana-indicator libdbusmenu-glib cairo harfbuzz libepoxy \
          python python-gobject python-pycountry gtk4 libadwaita meson \
          cmake ninja qt6-base qt6-wayland vulkan-headers libdrm libxcb \
          polkit

    # مرحله 3: نصب yay
    - name: Install yay as builder user
      run: |
        useradd -m builder
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        sudo -u builder git clone https://aur.archlinux.org/yay.git /tmp/yay
        cd /tmp/yay
        sudo -u builder makepkg -si --noconfirm --skippgpcheck
        rm -rf /tmp/yay

    # مرحله 4: ساخت بسته‌های AUR
    - name: Build AUR packages with yay
      run: |
        cd "$GITHUB_WORKSPACE"
        sudo -u builder yay -S --noconfirm --builddir=/tmp --mflags="--skippgpcheck" hiddify-app-bin
        sudo -u builder yay -S --noconfirm --builddir=/tmp --mflags="--skippgpcheck" carburetor
        sudo -u builder yay -S --noconfirm --builddir=/tmp --mflags="--skippgpcheck" lact-git
        sudo -u builder yay -S --noconfirm --builddir=/tmp --mflags="--skippgpcheck" oblivion-desktop-bin

    # مرحله 5: آماده‌سازی مخزن
    - name: Prepare repository structure
      run: |
        # ایجاد ساختار دایرکتوری
        mkdir -p "$GITHUB_WORKSPACE/repo/x86_64"
        
        # کپی بسته‌ها (به جای جابجایی برای اطمینان از دسترسی)
        find /tmp -name "*.pkg.tar.zst" -exec cp {} "$GITHUB_WORKSPACE/repo/x86_64/" \;
        
        # ایجاد دیتابیس مخزن
        cd "$GITHUB_WORKSPACE/repo/x86_64"
        
        # حذف فایل‌های قدیمی
        rm -f *.db *.files *.db.tar.gz *.files.tar.gz
        
        # ایجاد دیتابیس جدید بدون امضا
        repo-add -n zc-repo.db.tar.gz *.pkg.tar.zst
        
        # ایجاد لینک‌های سمبولیک
        ln -sv zc-repo.db.tar.gz zc-repo.db
        ln -sv zc-repo.files.tar.gz zc-repo.files
        
        # بررسی محتویات
        echo "محتوای مخزن:"
        ls -la
        echo "محتوای دیتابیس:"
        tar -ztvf zc-repo.db.tar.gz

    # مرحله 6: آپلود به Codeberg
    - name: Push to Codeberg
      env:
        CODEBERG_USER: zenoralinux
        CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
      run: |
        cd "$GITHUB_WORKSPACE/repo"
        
        # پیکربندی Git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global init.defaultBranch main
        
        # مقداردهی اولیه مخزن
        git init
        git checkout -b main
        git add .
        git commit -m "آپدیت خودکار: $(date +'%Y-%m-%d %H:%M:%S')"
        
        # آپلود با احراز هویت
        git remote add origin "https://${CODEBERG_USER}:${CODEBERG_TOKEN}@codeberg.org/${CODEBERG_USER}/zc-repo.git"
        git push -u origin main --force
        
        echo "مخزن با موفقیت آپدیت شد!"
        echo "آدرس مخزن: https://codeberg.org/zenoralinux/zc-repo"
