name: zenora Linux Repository Builder

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily

jobs:
  build-repo:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # [Previous steps remain unchanged until the repository handling...]

    - name: Setup and Clone Repository
      env:
        CODEBERG_USER: zenoralinux
        CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
      run: |
        # Clean token
        CLEAN_TOKEN=$(echo "$CODEBERG_TOKEN" | tr -d '\n\r\t ')
        
        # Git config
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Debug: Show current directory
        echo "Current directory: $(pwd)"
        ls -la
        
        # Initialize or clone repository
        if [ ! -d existing_repo ]; then
          echo "Cloning repository..."
          git clone "https://${CODEBERG_USER}:${CLEAN_TOKEN}@codeberg.org/${CODEBERG_USER}/zc-repo.git" existing_repo || \
          {
            echo "Clone failed, initializing new repository..."
            mkdir -p existing_repo/zcrepo/x86_64
            cd existing_repo
            git init
            git remote add origin "https://${CODEBERG_USER}:${CLEAN_TOKEN}@codeberg.org/${CODEBERG_USER}/zc-repo.git"
            touch README.md
            git add .
            git commit -m "Initial commit"
          }
        else
          echo "Repository already exists"
          cd existing_repo
          git remote set-url origin "https://${CODEBERG_USER}:${CLEAN_TOKEN}@codeberg.org/${CODEBERG_USER}/zc-repo.git"
          git fetch
          git checkout main
        fi

        # Verify repository setup
        cd existing_repo
        echo "Repository status:"
        git status
        echo "Remote info:"
        git remote -v

    - name: Copy x86_64 packages
      run: |
        echo "Copying x86_64 packages..."
        mkdir -p existing_repo/zcrepo/x86_64
        find /tmp -name "*.pkg.tar.zst" -exec cp -fv {} existing_repo/zcrepo/x86_64/ \;
        
        cd existing_repo/zcrepo/x86_64
        echo "Current package files:"
        ls -la
        
        echo "Rebuilding repository database..."
        rm -f zc-repo.db* zc-repo.files*
        repo-add zc-repo.db.tar.gz *.pkg.tar.zst || echo "No packages found for x86_64"
        [ -f zc-repo.files.tar.gz ] && mv zc-repo.files.tar.gz zc-repo.files
        [ -f zc-repo.db.tar.gz ] && mv zc-repo.db.tar.gz zc-repo.db

    - name: Copy aarch64 packages
      run: |
        echo "Copying aarch64 packages..."
        mkdir -p existing_repo/zcrepo/aarch64
        find /tmp -name "*any.pkg.tar.zst" -exec cp -fv {} existing_repo/zcrepo/aarch64/ \;
        find /tmp -name "*aarch64.pkg.tar.zst" -exec cp -fv {} existing_repo/zcrepo/aarch64/ \;
        
        cd existing_repo/zcrepo/aarch64
        echo "Current package files:"
        ls -la
        
        echo "Rebuilding repository database..."
        rm -f zc-repo.db* zc-repo.files*
        repo-add zc-repo.db.tar.gz *.pkg.tar.zst || echo "No packages found for aarch64"
        [ -f zc-repo.files.tar.gz ] && mv zc-repo.files.tar.gz zc-repo.files
        [ -f zc-repo.db.tar.gz ] && mv zc-repo.db.tar.gz zc-repo.db

    - name: Push changes
      run: |
        cd existing_repo
        echo "Current directory: $(pwd)"
        
        # Verify git status
        echo "Git status before add:"
        git status
        
        # Add all changes
        git add .
        
        echo "Git status after add:"
        git status
        
        # Commit changes
        git commit -m "Automated update: $(date +'%Y-%m-%d %H:%M:%S')" || \
          { echo "No changes to commit"; exit 0; }
        
        # Pull latest changes
        git pull --rebase origin main || \
          { echo "Pull failed, attempting force push"; git push --force origin main; exit 0; }
        
        # Push changes
        git push origin main
        
        echo "Repository successfully updated!"
        echo "Access at: https://codeberg.org/zenoralinux/zc-repo/tree/main/zcrepo/"
