name: Build AUR Package

on:
  push:
  schedule:
    - cron: '0 0 * * *'  # Run daily

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        pacman -Sy --noconfirm --needed git base-devel pacman-contrib
        
    - name: Clone AUR package
      run: |
        git clone https://aur.archlinux.org/hiddify-app-bin.git
        
    - name: Build package
      working-directory: ./hiddify-app-bin
      run: |
        # Add build user to avoid running as root
        useradd -m builder
        chown -R builder .
        su builder -c "makepkg -s --noconfirm"
        
    - name: Prepare repo directory
      run: |
        mkdir -p x86_64
        
    - name: Move package to repo
      run: |
        mv hiddify-app-bin/*.pkg.tar.zst x86_64/
        
    - name: Create repository database
      run: |
        cd x86_64
        repo-add my-linux-repo.db.tar.gz *.pkg.tar.zst
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-repo
        path: x86_64
        retention-days: 5
