name: Arch Linux Repository Builder

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # روزانه اجرا شود

jobs:
  build-repo:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    # مرحله 1: دریافت مخزن با تمام تاریخچه
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # مرحله 2: تنظیم محیط ساخت
    - name: Setup build environment
      run: |
        pacman -Sy --noconfirm --needed git base-devel pacman-contrib
        pacman -S --noconfirm --needed \
          hicolor-icon-theme libayatana-appindicator at-spi2-core \
          fontconfig pango gtk3 ayatana-ido gdk-pixbuf2 \
          libayatana-indicator libdbusmenu-glib cairo harfbuzz libepoxy

    # مرحله 3: دریافت و ساخت بسته AUR
    - name: Clone and build AUR package
      run: |
        git clone https://aur.archlinux.org/hiddify-app-bin.git
        cd hiddify-app-bin
        useradd -m builder
        chown -R builder .
        su builder -c "makepkg -s --noconfirm --skippgpcheck"

    # مرحله 4: آماده‌سازی ریپازیتوری
    - name: Prepare repository structure
      run: |
        mkdir -p repo/x86_64
        mv hiddify-app-bin/*.pkg.tar.zst repo/x86_64/
        cd repo/x86_64
        repo-add hiddify-repo.db.tar.gz *.pkg.tar.zst

    # مرحله 5: آپلود به شاخه repo
    - name: Deploy to repository branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./repo
        destination_dir: .
        publish_branch: repo
        keep_files: false
        force_orphan: true
