name: Build AUR Package

on:
  push:
  schedule:
    - cron: '0 0 * * *'  # Run daily

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Configure pacman and install base dependencies
      run: |
        # Configure pacman to skip checks and run without sudo
        sed -i 's/^CheckSpace/#CheckSpace/' /etc/pacman.conf
        echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
        
        # Install all required dependencies first
        pacman -Sy --noconfirm --needed \
          git base-devel pacman-contrib \
          hicolor-icon-theme libayatana-appindicator at-spi2-core \
          fontconfig pango gtk3 ayatana-ido gdk-pixbuf2 \
          libayatana-indicator libdbusmenu-glib cairo harfbuzz libepoxy
        
    - name: Clone AUR package
      run: |
        git clone https://aur.archlinux.org/hiddify-app-bin.git
        
    - name: Build package as non-root user
      working-directory: ./hiddify-app-bin
      run: |
        # Create build user
        useradd -m builder
        chown -R builder .
        
        # Build as non-root user
        su builder -c "makepkg -s --noconfirm --skippgpcheck"
        
    - name: Prepare repo directory
      run: |
        mkdir -p x86_64
        
    - name: Move package to repo
      run: |
        mv hiddify-app-bin/*.pkg.tar.zst x86_64/
        
    - name: Create repository database
      run: |
        cd x86_64
        repo-add my-linux-repo.db.tar.gz *.pkg.tar.zst
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-repo
        path: x86_64
        retention-days: 5
