name: Arch Linux Repository Builder

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # روزانه اجرا شود

jobs:
  build-repo:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    # مرحله 1: دریافت مخزن و تنظیم Git LFS
    - name: Checkout repository + LFS
      uses: actions/checkout@v4
      with:
        lfs: true  # فعال‌سازی LFS

    # مرحله 2: تنظیم محیط ساخت
    - name: Setup build environment
      run: |
        pacman -Rdd --noconfirm systemd-sysvcompat || true
        pacman -Sy --noconfirm --needed git git-lfs base-devel
        git lfs install --skip-repo  # فعال‌سازی LFS در محیط اجرا
        pacman -S --noconfirm --needed \
          hicolor-icon-theme libayatana-appindicator at-spi2-core \
          fontconfig pango gtk3 ayatana-ido gdk-pixbuf2 \
          libayatana-indicator libdbusmenu-glib cairo harfbuzz libepoxy \
          python python-gobject python-pycountry gtk4 libadwaita meson \
          cmake ninja qt6-base qt6-wayland vulkan-headers libdrm libxcb \
          polkit

    # مرحله 3: نصب yay
    - name: Install yay as builder user
      run: |
        useradd -m builder
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        sudo -u builder git clone https://aur.archlinux.org/yay.git /tmp/yay
        cd /tmp/yay
        sudo -u builder makepkg -si --noconfirm --skippgpcheck
        rm -rf /tmp/yay

    # مرحله 4: ساخت بسته‌ها (شامل oblivion-desktop-bin)
    - name: Build AUR packages with yay
      run: |
        cd "$GITHUB_WORKSPACE"
        sudo -u builder yay -S --noconfirm --builddir=/tmp --mflags="--skippgpcheck" \
          hiddify-app-bin carburetor lact-git oblivion-desktop-bin

    # مرحله 5: آماده‌سازی ریپازیتوری با LFS
    - name: Prepare repository with LFS
      run: |
        mkdir -p "$GITHUB_WORKSPACE/repo/x86_64"
        find /tmp -name "*.pkg.tar.zst" -exec mv {} "$GITHUB_WORKSPACE/repo/x86_64/" \;
        cd "$GITHUB_WORKSPACE/repo/x86_64"
        git lfs track "*.pkg.tar.zst"  # اطمینان از LFS برای فایل‌ها
        repo-add zc-repo.db.tar.gz *.pkg.tar.zst

    # مرحله 6: آپلود با پشتیبانی از LFS
    - name: Deploy to repository branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.UPLOAD_ZENORA }}
        publish_dir: ./repo
        destination_dir: .
        publish_branch: repo
        keep_files: false
        force_orphan: true
