name: zenora ARM64 AUR Repository Builder

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Enable QEMU for aarch64
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build powerlevel10k for ARM64
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/fwcd/archlinux:latest
          options: --platform linux/arm64 --privileged -v ${{ github.workspace }}:/output
          shell: bash
          run: |
            set -eux
            pacman -Syu --noconfirm
            pacman -S --noconfirm sudo git base-devel wget archlinux-keyring cmake zsh pacman-contrib

            wget https://repo.archlinuxcn.org/aarch64/paru-git-2.0.4.r63.g5bca838-1-aarch64.pkg.tar.zst
            pacman -U ./paru-git-2.0.4.r63.g5bca838-1-aarch64.pkg.tar.zst --noconfirm
            
            useradd -m builder
            echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
            su - builder -c '
            paru --noconfirm --mflags="--skippgpcheck" --clonedir /tmp -S zsh-theme-powerlevel10k
          
            ls
            '
  
      # ✅ مرحله نهایی: سینک با Codeberg
      - name: Prepare and Sync Repository
        env:
          CODEBERG_USER: zenoralinux
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          set -eux
          CLEAN_TOKEN=$(echo "$CODEBERG_TOKEN" | tr -d '\n\r\t ')
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          cd "$GITHUB_WORKSPACE"
          git clone "https://${CODEBERG_USER}:${CLEAN_TOKEN}@codeberg.org/${CODEBERG_USER}/zc-repo.git" existing_repo

          mkdir -p existing_repo/zcrepo/aarch64
          sudo find /tmp -name "*aarch64.pkg.tar.zst" -exec cp -f {} existing_repo/zcrepo/aarch64/ \;
          sudo find /tmp -name "*any.pkg.tar.zst" -exec cp -f {} existing_repo/zcrepo/aarch64/ \;
          sudo find /tmp -name "*aarch64.pkg.tar.xz" -exec cp -f {} existing_repo/zcrepo/aarch64/ \;
          cd existing_repo/zcrepo/aarch64
          rm -f zc-repo.db* zc-repo.files*
          repo-add zc-repo.db.tar.gz *.pkg.tar.zst
          mv zc-repo.files.tar.gz zc-repo.files
          mv zc-repo.db.tar.gz zc-repo.db

          cd ../../
          # پاکسازی توکن
          CLEAN_TOKEN=$(echo "$CODEBERG_TOKEN" | tr -d '\n\r\t ')

          # Push به Codeberg
          git remote set-url origin "https://${CODEBERG_USER}:${CLEAN_TOKEN}@codeberg.org/${CODEBERG_USER}/zc-repo.git"
          git add .
          git commit -m "Automated update: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin main

          echo "Repository successfully synced!"
