name: zenora ARM64 AUR Repository Builder
  
on: 
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Enable QEMU for aarch64
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build powerlevel10k for ARM64
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/fwcd/archlinux:latest
          options: --platform linux/arm64 --privileged -v ${{ github.workspace }}:/output
          shell: bash
          run: |
            set -eux
            sed -i '/^\[core\]/i\
            [archlinuxcn]\
            SigLevel = Never\
            Server = https://repo.archlinuxcn.org/$arch' /etc/pacman.conf
          
            pacman -Syu --noconfirm
            pacman -S --noconfirm sudo git base-devel wget archlinux-keyring cmake zsh pacman-contrib paru-git
            useradd -m builder
            echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
            su - builder -c '
              paru --noconfirm --mflags="--skippgpcheck" --clonedir /tmp -S zsh-theme-powerlevel10k
            '

            mkdir -p /output/packages
            find /tmp -name "*.pkg.tar.*" -exec cp -v {} /output/packages/ \;

      - name: Prepare and Sync Repository in Arch Container
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest
          options: -v ${{ github.workspace }}:/workspace
          shell: bash
          run: |
            set -eux
            pacman -Sy --noconfirm git pacman-contrib

            export CODEBERG_USER="zenoralinux"
            export CLEAN_TOKEN="$(echo "${{ secrets.CODEBERG_TOKEN }}" | tr -d '\n\r\t ')"

            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"

            cd /workspace
            rm -rf existing_repo
            git clone "https://${CODEBERG_USER}:${CLEAN_TOKEN}@codeberg.org/${CODEBERG_USER}/zc-repo.git" existing_repo

            mkdir -p existing_repo/zcrepo/aarch64
            cp -v /workspace/packages/*.pkg.tar.* existing_repo/zcrepo/aarch64/

            cd existing_repo/zcrepo/aarch64
            rm -f zc-repo.db* zc-repo.files*
            repo-add zc-repo.db.tar.gz *.pkg.tar.* || repo-add zc-repo.db.tar.gz *.pkg.tar.*
            mv zc-repo.files.tar.gz zc-repo.files || true
            mv zc-repo.db.tar.gz zc-repo.db || true

            cd ../../
            git add .
            git commit -m "Automated update: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
            git push origin main

            echo "✅ Repository successfully synced!"
